#!/bin/bash

mkdir -p /tmp/rom # Where to sync source
cd /tmp/rom

SECONDS=0

if [[ $git_cookies != 0 ]]; then

sudo touch /etc/mtab
sudo chmod 777 /etc/mtab

echo "$git_cookies" > ~/git_cookies.sh
bash ~/git_cookies.sh

fi

# Sync source
repo init --depth=1 --no-repo-verify -u https://github.com/DerpFest-AOSP/manifest.git -b 13 -g default,-mips,-darwin,-notdefault
git clone https://github.com/wHo-EM-i/manifest.git --depth 1 -b 13-4.19-common .repo/local_manifests

# Sync source without unnecessary messages, try with -j16 first, if fails, it will try again
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j16 || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j10

# clo-powerhal
rm -rf /tmp/rom/vendor/qcom/opensource/power
git clone --depth=1 https://github.com/wHo-EM-i/android_vendor_qcom-opensource_power -b topaz /tmp/rom/vendor/qcom/opensource/power

# tree
git clone --depth=1 https://wHo-EM-i:$my_og_token@github.com/wHo-EM-i/android_device_xiaomi_lavender -b derp /tmp/rom/device/xiaomi/lavender
# cmn-tree
git clone --depth=1 https://wHo-EM-i:$my_og_token@github.com/wHo-EM-i/device_sdm660-common -b 13-4.19 /tmp/rom/device/xiaomi/sdm660-common
#los-shit
rm -rf /tmp/rom/device/xiaomi/sdm660-common/libhidl

#hals
rm -rf /tmp/rom/hardware/qcom-caf/sdm660
git clone --depth=1 https://github.com/wHo-EM-i/android_hardware_qcom_audio /tmp/rom/hardware/qcom-caf/sdm660/audio -b 13-caf-sdm660
git clone --depth=1 https://github.com/wHo-EM-i/android_hardware_qcom_display /tmp/rom/hardware/qcom-caf/sdm660/display -b 13-caf_4.19
git clone --depth=1 https://github.com/wHo-EM-i/android_hardware_qcom_media /tmp/rom/hardware/qcom-caf/sdm660/media -b 13-caf-sdm660


# patch
cd /tmp/rom/system/libhidl && curl https://github.com/ArrowOS/android_system_libhidl/commit/fbdf10a33f546d202ae12b4b864177fea9faa998.patch | git am
#cd /tmp/rom/device/qcom/common && curl https://github.com/wHo-EM-i/android_device_qcom_common/commit/b3a612e836ddf3e9ac766612ee4bd9194b681c95.patch | git am
#cd /tmp/rom/bionic && curl https://github.com/wHo-EM-i/bionic/commit/5d7113e5323cfd9ad528319008b2895f5ac29113.patch | git am
#cd /tmp/rom/bionic && curl https://github.com/wHo-EM-i/bionic/commit/2fa9b6e73c2f0c2b21b529a14e886ac79e5a081f.patch | git am
#cd /tmp/rom/hardware/libhardware && curl https://github.com/AOSPA/android_hardware_libhardware/commit/bec92996fbc143620da9a4a3c22a744958535ad5.patch | git am

. /tmp/ci/function
tg "$rom_name source sync completed!
Total Size: $(du -sh /tmp/rom | cut -d - -f 1 | cut -d / -f 1)
Time Took: $(($SECONDS / 60)) minute(s) and $(($SECONDS % 60)) second(s).
Status: $progress"

echo "$(($SECONDS / 60))" > /tmp/sync_time.txt
