#!/bin/bash

mkdir -p /tmp/rom # Where to sync source
cd /tmp/rom

SECONDS=0

if [[ $git_cookies != 0 ]]; then

sudo touch /etc/mtab
sudo chmod 777 /etc/mtab

echo "$git_cookies" > ~/git_cookies.sh
bash ~/git_cookies.sh

fi

## Sync source
repo init --depth=1 --no-repo-verify -u https://github.com/DerpFest-AOSP/manifest.git -b 13 -g default,-mips,-darwin,-notdefault
#git clone https://github.com/Prashant-1695/local_manifest.git --depth 1 -b derp .repo/local_manifests

# Sync source without unnecessary messages, try with -j30 first, if fails, it will try again
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j10 || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j10

# trees
git clone --depth=1 https://ImSpiDy:$my_og_token@github.com/ImSpiDy/device_xiaomi_lavender device/xiaomi/lavender -b T
git clone --depth=1 https://ImSpiDy:$my_og_token@github.com/ImSpiDy/vendor_xiaomi_lavender-13 vendor/xiaomi/lavender -b T
git clone --depth=1 https://github.com/projects-nexus/xtreme_kernel_lavender-4.4 kernel/xiaomi/lavender -b a13-qti-camfix
git clone --depth=1 https://gitlab.com/Project-Nexus/nexus-clang.git prebuilts/clang/host/linux-x86/nexus-clang

# drop
rm -rf /tmp/rom/device/xiaomi/lavender/libhidl/Android.bp

. /tmp/ci/function
tg "$rom_name source sync completed!
Total Size: $(du -sh /tmp/rom | cut -d - -f 1 | cut -d / -f 1)
Time Took: $(($SECONDS / 60)) minute(s) and $(($SECONDS % 60)) second(s).
Status: $progress"

echo "$(($SECONDS / 60))" > /tmp/sync_time.txt
